-- Create table for Stock Fundamentalist Data
-- Compatible with PostgreSQL / Supabase

CREATE TABLE IF NOT EXISTS stock_fundamentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Identification
    papel VARCHAR(20) NOT NULL UNIQUE,
    tipo VARCHAR(10),
    empresa VARCHAR(255),
    setor VARCHAR(100),
    subsetor VARCHAR(100),
    
    -- Market Value
    valor_mercado BIGINT,
    valor_firma BIGINT,
    cotacao DECIMAL(10, 2),
    data_ultima_cotacao DATE,
    min_52_semanas DECIMAL(10, 2),
    max_52_semanas DECIMAL(10, 2),
    volume_medio_2m BIGINT,
    
    -- Price Oscillations (Stored as decimals, e.g., 0.05 for 5%)
    osc_dia DECIMAL(10, 4),
    osc_mes DECIMAL(10, 4),
    osc_30_dias DECIMAL(10, 4),
    osc_12_meses DECIMAL(10, 4),
    osc_2025 DECIMAL(10, 4),
    osc_2024 DECIMAL(10, 4),
    osc_2023 DECIMAL(10, 4),
    osc_2022 DECIMAL(10, 4),
    osc_2021 DECIMAL(10, 4),
    osc_2020 DECIMAL(10, 4),
    
    -- Balance Sheet
    ativo BIGINT,
    disponibilidades BIGINT,
    ativo_circulante BIGINT,
    divida_bruta BIGINT,
    divida_liquida BIGINT,
    patrimonio_liquido BIGINT,
    
    -- Financial Results (Last 12 Months)
    receita_liquida_12m BIGINT,
    ebit_12m BIGINT,
    lucro_liquido_12m BIGINT,
    
    -- Financial Results (Last 3 Months)
    receita_liquida_3m BIGINT,
    ebit_3m BIGINT,
    lucro_liquido_3m BIGINT,
    
    -- Valuation Multiples
    p_l DECIMAL(10, 2),
    p_vp DECIMAL(10, 2),
    p_ebit DECIMAL(10, 2),
    psr DECIMAL(10, 2),
    p_ativos DECIMAL(10, 2),
    p_cap_giro DECIMAL(10, 2),
    p_ativ_circ_liq DECIMAL(10, 2),
    div_yield DECIMAL(10, 4),
    ev_ebitda DECIMAL(10, 2),
    ev_ebit DECIMAL(10, 2),
    
    -- Performance Indicators
    lpa DECIMAL(10, 2),
    vpa DECIMAL(10, 2),
    marg_bruta DECIMAL(10, 4),
    marg_ebit DECIMAL(10, 4),
    marg_liquida DECIMAL(10, 4),
    ebit_ativo DECIMAL(10, 4),
    roic DECIMAL(10, 4),
    roe DECIMAL(10, 4),
    liquidez_corrente DECIMAL(10, 2),
    div_br_patrim DECIMAL(10, 2),
    giro_ativos DECIMAL(10, 2),
    cres_rec_5a DECIMAL(10, 4),
    
    -- Metadata
    data_ultimo_balanco DATE,
    numero_acoes BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index on ticker for faster lookups
CREATE INDEX IF NOT EXISTS idx_stock_fundamentals_papel ON stock_fundamentals(papel);

-- Comment on table
COMMENT ON TABLE stock_fundamentals IS 'Stores fundamentalist data for Brazilian stocks imported from Excel';
